server:
  port: 8080

spring:
  application:
    name: order-management-system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  region: us-east-1
  dynamodb:
    table-name: orders
  s3:
    bucket-name: order-invoices
  sns:
    topic-arn: arn:aws:sns:us-east-1:your-account-id:order-notifications

# JWT Configuration
jwt:
  secret: your-256-bit-secret
  expiration: 86400000 # 24 hours in milliseconds

# Swagger UI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Logging Configuration
logging:
  level:
    com.ordermanagement: DEBUG
    org.springframework: INFO 